### ISSUE TITLE
Doesn't seems to work on Safari

### ISSUE THREAD

**Issue by namlook** [vue-bulma/brace#2]
I tried the demo on Safari (and iOS 10) but the component doesn't seems to work. I simply can't write anything on the textfield.

It is working on Google Chrome though.

**Comment by luventa** [comment]
I will check on Safari late. Thanks for reporting this.

**Comment by fundon** [comment]
Landed in https://github.com/vue-bulma/vue-admin/commit/466a212a1908ca4d8a8c901089997bbbd6f8d607.
